{
  "IDENTIFIER": "IDENTIFIER",
  "OPEN_PAREN": "OPEN_PAREN",
  "STRING": "STRING",
  "CLOSE_PAREN": "CLOSE_PAREN",
  "BOOLEAN": "BOOLEAN",
  "NUMBER": "NUMBER",
  "STMT_END": "STMT_END",
  "OPERATOR": "OPERATOR",
}
