module.exports = {
  IDENTIFIER: "IDENTIFIER",
  OPEN_PAREN: "OPEN_PAREN",
  CLOSE_PAREN: "CLOSE_PAREN",
  STRING: "STRING",
  BOOLEAN: "BOOLEAN",
  NUMBER: "NUMBER",
  OPERATOR: "OPERATOR",
  STMT_END: "STMT_END",
  VARIABLE: "VARIABLE"
}
